package main

import (
	"database/sql"
	"fmt"
	"log"
	"os"

	"github.com/anthropics/anthropic-sdk-go"
	"github.com/joho/godotenv"

	"github.com/aschepis/backscratcher/staff/agent"
	"github.com/aschepis/backscratcher/staff/logger"
	"github.com/aschepis/backscratcher/staff/memory"
	"github.com/aschepis/backscratcher/staff/memory/ollama"
	"github.com/aschepis/backscratcher/staff/ui"
	"github.com/aschepis/backscratcher/staff/ui/tui"
	_ "github.com/mattn/go-sqlite3"
)

func main() {
	// Initialize logger
	if err := logger.Init(); err != nil {
		log.Fatalf("Failed to initialize logger: %v", err)
	}
	defer logger.Close()

	logger.Info("Starting Staff application")

	// Load dotenv
	_ = godotenv.Load("../.env")
	_ = godotenv.Load()

	anthropicAPIKey := os.Getenv("ANTHROPIC_API_KEY")
	if anthropicAPIKey == "" {
		logger.Error("Missing ANTHROPIC_API_KEY")
		log.Fatalf("Missing ANTHROPIC_API_KEY")
	}

	// ---------------------------
	// 1. Open SQLite + Memory Store
	// ---------------------------

	logger.Info("Initializing database and memory store")
	db, err := sql.Open("sqlite3", "staff_memory.db")
	if err != nil {
		logger.Error("Failed to open database: %v", err)
		log.Fatalf("Failed to open database: %v", err)
	}
	defer db.Close()

	embedder, err := ollama.NewEmbedder(ollama.ModelMXBAI)
	if err != nil {
		logger.Error("Failed to create ollama embedder: %v", err)
		log.Fatalf("Failed to create ollama embedder: %v", err)
	}

	store, err := memory.NewStore(db, embedder)
	if err != nil {
		logger.Error("Failed to create memory store: %v", err)
		log.Fatalf("Failed to create memory store: %v", err)
	}

	memoryRouter := memory.NewMemoryRouter(store, memory.Config{
		Summarizer: memory.NewAnthropicSummarizer("claude-3.5-haiku-latest", anthropicAPIKey, 256),
	})

	// ---------------------------
	// 2. Create Crew + Shared Tools
	// ---------------------------

	logger.Info("Creating crew and registering tools")
	crew := agent.NewCrew(anthropicAPIKey)

	// Register memory tools into shared registry
	crew.ToolRegistry.RegisterMemoryTools(memoryRouter)

	// Register schemas for memory tools
	// (Ideally autogenerated, but here explicitly)
	// Note: Tool names must match pattern ^[a-zA-Z0-9_-]{1,128}$ (no dots allowed)
	crew.ToolProvider.RegisterSchema("memory_search", agent.ToolSchema{
		Description: "Search the agent or global memory store.",
		Schema: map[string]any{
			"type": "object",
			"properties": map[string]any{
				"query":          map[string]any{"type": "string"},
				"include_global": map[string]any{"type": "boolean"},
				"limit":          map[string]any{"type": "number"},
			},
			"required": []string{"query"},
		},
	})

	crew.ToolProvider.RegisterSchema("memory_remember_fact", agent.ToolSchema{
		Description: "Store a global factual memory about the user.",
		Schema: map[string]any{
			"type": "object",
			"properties": map[string]any{
				"fact": map[string]any{"type": "string"},
			},
			"required": []string{"fact"},
		},
	})

	// ---------------------------
	// 3. Load Agents (from code for now)
	// ---------------------------

	logger.Info("Loading agent configuration")
	cfg := agent.CrewConfig{
		Agents: map[string]*agent.AgentConfig{
			"interviewer": {
				ID:   "interviewer",
				Name: "Interviewer Agent",
				System: `You are an interviewer who asks questions to the user in order to learn more
						 about them and records the answers in a structured format. You sometimes ask
						 follow-up questions to the user.`,
				Model:     string(anthropic.ModelClaudeSonnet4_20250514),
				MaxTokens: 2048,
				Tools:     []string{"memory_search", "memory_remember_fact"},
			},
			// "planner": {
			// 	ID:        "planner",
			// 	Name:      "Planning Agent",
			// 	System:    "You help plan tasks and break down user goals.",
			// 	Model:     string(anthropic.ModelClaudeSonnet4_20250514),
			// 	MaxTokens: 2048,
			// 	Tools:     []string{"memory_search"},
			// },
		},
	}

	if err := crew.LoadCrewConfig(cfg); err != nil {
		logger.Error("Failed to load crew config: %v", err)
		log.Fatalf("Failed to load crew config: %v", err)
	}

	// Initialize AgentRunners
	if err := crew.InitializeAgents(); err != nil {
		logger.Error("Failed to initialize agents: %v", err)
		log.Fatalf("Failed to initialize agents: %v", err)
	}

	logger.Info("Agents initialized successfully")

	// ---------------------------
	// 4. Create UI Service and TUI
	// ---------------------------

	logger.Info("Initializing UI")
	// Suppress console output to avoid interfering with TUI rendering
	logger.SetSuppressConsole(true)

	chatService := ui.NewChatService(crew)
	app := tui.NewApp(chatService)

	logger.Info("Starting terminal UI")
	if err := app.Run(); err != nil {
		logger.Error("Error running application: %v", err)
		fmt.Fprintf(os.Stderr, "Error running application: %v\n", err)
		os.Exit(1)
	}

	logger.Info("Application shutdown")
}
