// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: staff.proto

package staffpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatRequest - Send a message to an agent
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_staff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ChatRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ChatEvent - Streaming events from agent
type ChatEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ChatEvent_TextDelta
	//	*ChatEvent_ToolUse
	//	*ChatEvent_ToolResult
	//	*ChatEvent_Complete
	//	*ChatEvent_Error
	Event         isChatEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_staff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{1}
}

func (x *ChatEvent) GetEvent() isChatEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ChatEvent) GetTextDelta() *TextDelta {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_TextDelta); ok {
			return x.TextDelta
		}
	}
	return nil
}

func (x *ChatEvent) GetToolUse() *ToolUse {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_ToolUse); ok {
			return x.ToolUse
		}
	}
	return nil
}

func (x *ChatEvent) GetToolResult() *ToolResult {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *ChatEvent) GetComplete() *ChatComplete {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *ChatEvent) GetError() *ChatError {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isChatEvent_Event interface {
	isChatEvent_Event()
}

type ChatEvent_TextDelta struct {
	TextDelta *TextDelta `protobuf:"bytes,1,opt,name=text_delta,json=textDelta,proto3,oneof"`
}

type ChatEvent_ToolUse struct {
	ToolUse *ToolUse `protobuf:"bytes,2,opt,name=tool_use,json=toolUse,proto3,oneof"`
}

type ChatEvent_ToolResult struct {
	ToolResult *ToolResult `protobuf:"bytes,3,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type ChatEvent_Complete struct {
	Complete *ChatComplete `protobuf:"bytes,4,opt,name=complete,proto3,oneof"`
}

type ChatEvent_Error struct {
	Error *ChatError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*ChatEvent_TextDelta) isChatEvent_Event() {}

func (*ChatEvent_ToolUse) isChatEvent_Event() {}

func (*ChatEvent_ToolResult) isChatEvent_Event() {}

func (*ChatEvent_Complete) isChatEvent_Event() {}

func (*ChatEvent_Error) isChatEvent_Event() {}

type TextDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextDelta) Reset() {
	*x = TextDelta{}
	mi := &file_staff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextDelta) ProtoMessage() {}

func (x *TextDelta) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextDelta.ProtoReflect.Descriptor instead.
func (*TextDelta) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{2}
}

func (x *TextDelta) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ToolUse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Input         string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"` // JSON-encoded input
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolUse) Reset() {
	*x = ToolUse{}
	mi := &file_staff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolUse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolUse) ProtoMessage() {}

func (x *ToolUse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolUse.ProtoReflect.Descriptor instead.
func (*ToolUse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{3}
}

func (x *ToolUse) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ToolUse) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolUse) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	IsError       bool                   `protobuf:"varint,4,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_staff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{4}
}

func (x *ToolResult) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ToolResult) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type ChatComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	InputTokens   int32                  `protobuf:"varint,2,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,3,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatComplete) Reset() {
	*x = ChatComplete{}
	mi := &file_staff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatComplete) ProtoMessage() {}

func (x *ChatComplete) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatComplete.ProtoReflect.Descriptor instead.
func (*ChatComplete) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{5}
}

func (x *ChatComplete) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ChatComplete) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *ChatComplete) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

type ChatError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatError) Reset() {
	*x = ChatError{}
	mi := &file_staff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatError) ProtoMessage() {}

func (x *ChatError) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatError.ProtoReflect.Descriptor instead.
func (*ChatError) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{6}
}

func (x *ChatError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Thread management
type GetThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"` // Optional - if empty, creates new thread
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreadRequest) Reset() {
	*x = GetThreadRequest{}
	mi := &file_staff_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadRequest) ProtoMessage() {}

func (x *GetThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadRequest.ProtoReflect.Descriptor instead.
func (*GetThreadRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{7}
}

func (x *GetThreadRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type ThreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadResponse) Reset() {
	*x = ThreadResponse{}
	mi := &file_staff_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadResponse) ProtoMessage() {}

func (x *ThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadResponse.ProtoReflect.Descriptor instead.
func (*ThreadResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{8}
}

func (x *ThreadResponse) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ThreadResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ThreadResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ThreadResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type LoadHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // 0 = no limit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadHistoryRequest) Reset() {
	*x = LoadHistoryRequest{}
	mi := &file_staff_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadHistoryRequest) ProtoMessage() {}

func (x *LoadHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadHistoryRequest.ProtoReflect.Descriptor instead.
func (*LoadHistoryRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{9}
}

func (x *LoadHistoryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LoadHistoryRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *LoadHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LoadHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadHistoryResponse) Reset() {
	*x = LoadHistoryResponse{}
	mi := &file_staff_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadHistoryResponse) ProtoMessage() {}

func (x *LoadHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadHistoryResponse.ProtoReflect.Descriptor instead.
func (*LoadHistoryResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{10}
}

func (x *LoadHistoryResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "user", "assistant", "system"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_staff_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{11}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Context management
type ContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextRequest) Reset() {
	*x = ContextRequest{}
	mi := &file_staff_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextRequest) ProtoMessage() {}

func (x *ContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextRequest.ProtoReflect.Descriptor instead.
func (*ContextRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{12}
}

func (x *ContextRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ContextRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type ContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TokensBefore  int32                  `protobuf:"varint,3,opt,name=tokens_before,json=tokensBefore,proto3" json:"tokens_before,omitempty"`
	TokensAfter   int32                  `protobuf:"varint,4,opt,name=tokens_after,json=tokensAfter,proto3" json:"tokens_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextResponse) Reset() {
	*x = ContextResponse{}
	mi := &file_staff_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextResponse) ProtoMessage() {}

func (x *ContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextResponse.ProtoReflect.Descriptor instead.
func (*ContextResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{13}
}

func (x *ContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ContextResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ContextResponse) GetTokensBefore() int32 {
	if x != nil {
		return x.TokensBefore
	}
	return 0
}

func (x *ContextResponse) GetTokensAfter() int32 {
	if x != nil {
		return x.TokensAfter
	}
	return 0
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_staff_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{14}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_staff_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{15}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Schedulable   bool                   `protobuf:"varint,5,opt,name=schedulable,proto3" json:"schedulable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_staff_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{16}
}

func (x *AgentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentInfo) GetSchedulable() bool {
	if x != nil {
		return x.Schedulable
	}
	return false
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_staff_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{17}
}

func (x *GetStateRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type AgentState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "idle", "running", "paused", "error"
	CurrentTask   string                 `protobuf:"bytes,3,opt,name=current_task,json=currentTask,proto3" json:"current_task,omitempty"`
	LastRun       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	NextRun       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=next_run,json=nextRun,proto3" json:"next_run,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentState) Reset() {
	*x = AgentState{}
	mi := &file_staff_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentState) ProtoMessage() {}

func (x *AgentState) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentState.ProtoReflect.Descriptor instead.
func (*AgentState) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{18}
}

func (x *AgentState) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentState) GetCurrentTask() string {
	if x != nil {
		return x.CurrentTask
	}
	return ""
}

func (x *AgentState) GetLastRun() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRun
	}
	return nil
}

func (x *AgentState) GetNextRun() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRun
	}
	return nil
}

func (x *AgentState) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type WatchStatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentIds      []string               `protobuf:"bytes,1,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"` // Empty = watch all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchStatesRequest) Reset() {
	*x = WatchStatesRequest{}
	mi := &file_staff_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStatesRequest) ProtoMessage() {}

func (x *WatchStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStatesRequest.ProtoReflect.Descriptor instead.
func (*WatchStatesRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{19}
}

func (x *WatchStatesRequest) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

type ListInboxRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeArchived bool                   `protobuf:"varint,1,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	Limit           int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset          int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListInboxRequest) Reset() {
	*x = ListInboxRequest{}
	mi := &file_staff_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInboxRequest) ProtoMessage() {}

func (x *ListInboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInboxRequest.ProtoReflect.Descriptor instead.
func (*ListInboxRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{20}
}

func (x *ListInboxRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

func (x *ListInboxRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListInboxRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListInboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*InboxItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInboxResponse) Reset() {
	*x = ListInboxResponse{}
	mi := &file_staff_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInboxResponse) ProtoMessage() {}

func (x *ListInboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInboxResponse.ProtoReflect.Descriptor instead.
func (*ListInboxResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{21}
}

func (x *ListInboxResponse) GetItems() []*InboxItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListInboxResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type InboxItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"` // "low", "normal", "high", "urgent"
	Archived      bool                   `protobuf:"varint,6,opt,name=archived,proto3" json:"archived,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxItem) Reset() {
	*x = InboxItem{}
	mi := &file_staff_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxItem) ProtoMessage() {}

func (x *InboxItem) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxItem.ProtoReflect.Descriptor instead.
func (*InboxItem) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{22}
}

func (x *InboxItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InboxItem) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *InboxItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InboxItem) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *InboxItem) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *InboxItem) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *InboxItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ArchiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveRequest) Reset() {
	*x = ArchiveRequest{}
	mi := &file_staff_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRequest) ProtoMessage() {}

func (x *ArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRequest.ProtoReflect.Descriptor instead.
func (*ArchiveRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{23}
}

func (x *ArchiveRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type ArchiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveResponse) Reset() {
	*x = ArchiveResponse{}
	mi := &file_staff_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveResponse) ProtoMessage() {}

func (x *ArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveResponse.ProtoReflect.Descriptor instead.
func (*ArchiveResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{24}
}

func (x *ArchiveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WatchInboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentIds      []string               `protobuf:"bytes,1,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"` // Empty = watch all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchInboxRequest) Reset() {
	*x = WatchInboxRequest{}
	mi := &file_staff_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchInboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchInboxRequest) ProtoMessage() {}

func (x *WatchInboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchInboxRequest.ProtoReflect.Descriptor instead.
func (*WatchInboxRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{25}
}

func (x *WatchInboxRequest) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	MemoryType    string                 `protobuf:"bytes,2,opt,name=memory_type,json=memoryType,proto3" json:"memory_type,omitempty"` // "personal", "agent", "conversation", or empty for all
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`          // Filter by agent (optional)
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_staff_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{26}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetMemoryType() string {
	if x != nil {
		return x.MemoryType
	}
	return ""
}

func (x *SearchRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*MemoryResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_staff_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{27}
}

func (x *SearchResponse) GetResults() []*MemoryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type MemoryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MemoryType    string                 `protobuf:"bytes,3,opt,name=memory_type,json=memoryType,proto3" json:"memory_type,omitempty"`
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Score         float32                `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryResult) Reset() {
	*x = MemoryResult{}
	mi := &file_staff_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryResult) ProtoMessage() {}

func (x *MemoryResult) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryResult.ProtoReflect.Descriptor instead.
func (*MemoryResult) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{28}
}

func (x *MemoryResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryResult) GetMemoryType() string {
	if x != nil {
		return x.MemoryType
	}
	return ""
}

func (x *MemoryResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MemoryResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MemoryResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MemoryResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	MemoryType    string                 `protobuf:"bytes,2,opt,name=memory_type,json=memoryType,proto3" json:"memory_type,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_staff_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{29}
}

func (x *StoreRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoreRequest) GetMemoryType() string {
	if x != nil {
		return x.MemoryType
	}
	return ""
}

func (x *StoreRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StoreRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_staff_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{30}
}

func (x *StoreResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_staff_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{31}
}

type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	SocketPath    string                 `protobuf:"bytes,4,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
	Database      *DatabaseInfo          `protobuf:"bytes,5,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_staff_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{32}
}

func (x *SystemInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SystemInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SystemInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemInfo) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

func (x *SystemInfo) GetDatabase() *DatabaseInfo {
	if x != nil {
		return x.Database
	}
	return nil
}

type DatabaseInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Path              string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SizeBytes         int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	MemoryCount       int32                  `protobuf:"varint,3,opt,name=memory_count,json=memoryCount,proto3" json:"memory_count,omitempty"`
	ConversationCount int32                  `protobuf:"varint,4,opt,name=conversation_count,json=conversationCount,proto3" json:"conversation_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DatabaseInfo) Reset() {
	*x = DatabaseInfo{}
	mi := &file_staff_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseInfo) ProtoMessage() {}

func (x *DatabaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseInfo.ProtoReflect.Descriptor instead.
func (*DatabaseInfo) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{33}
}

func (x *DatabaseInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DatabaseInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *DatabaseInfo) GetMemoryCount() int32 {
	if x != nil {
		return x.MemoryCount
	}
	return 0
}

func (x *DatabaseInfo) GetConversationCount() int32 {
	if x != nil {
		return x.ConversationCount
	}
	return 0
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Optional - filter by agent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_staff_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{34}
}

func (x *ListToolsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolInfo            `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_staff_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{35}
}

func (x *ListToolsResponse) GetTools() []*ToolInfo {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ToolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"` // "builtin", "mcp:<server_name>"
	Schema        string                 `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"` // JSON schema
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolInfo) Reset() {
	*x = ToolInfo{}
	mi := &file_staff_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInfo) ProtoMessage() {}

func (x *ToolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInfo.ProtoReflect.Descriptor instead.
func (*ToolInfo) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{36}
}

func (x *ToolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ToolInfo) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

var File_staff_proto protoreflect.FileDescriptor

const file_staff_proto_rawDesc = "" +
	"\n" +
	"\vstaff.proto\x12\bstaff.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"_\n" +
	"\vChatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x96\x02\n" +
	"\tChatEvent\x124\n" +
	"\n" +
	"text_delta\x18\x01 \x01(\v2\x13.staff.v1.TextDeltaH\x00R\ttextDelta\x12.\n" +
	"\btool_use\x18\x02 \x01(\v2\x11.staff.v1.ToolUseH\x00R\atoolUse\x127\n" +
	"\vtool_result\x18\x03 \x01(\v2\x14.staff.v1.ToolResultH\x00R\n" +
	"toolResult\x124\n" +
	"\bcomplete\x18\x04 \x01(\v2\x16.staff.v1.ChatCompleteH\x00R\bcomplete\x12+\n" +
	"\x05error\x18\x05 \x01(\v2\x13.staff.v1.ChatErrorH\x00R\x05errorB\a\n" +
	"\x05event\"\x1f\n" +
	"\tTextDelta\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"U\n" +
	"\aToolUse\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\"u\n" +
	"\n" +
	"ToolResult\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x19\n" +
	"\bis_error\x18\x04 \x01(\bR\aisError\"r\n" +
	"\fChatComplete\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12!\n" +
	"\finput_tokens\x18\x02 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x03 \x01(\x05R\foutputTokens\"9\n" +
	"\tChatError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"J\n" +
	"\x10GetThreadRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\"\xbe\x01\n" +
	"\x0eThreadResponse\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"b\n" +
	"\x12LoadHistoryRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"D\n" +
	"\x13LoadHistoryResponse\x12-\n" +
	"\bmessages\x18\x01 \x03(\v2\x11.staff.v1.MessageR\bmessages\"q\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"H\n" +
	"\x0eContextRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\"\x8d\x01\n" +
	"\x0fContextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rtokens_before\x18\x03 \x01(\x05R\ftokensBefore\x12!\n" +
	"\ftokens_after\x18\x04 \x01(\x05R\vtokensAfter\"\x13\n" +
	"\x11ListAgentsRequest\"A\n" +
	"\x12ListAgentsResponse\x12+\n" +
	"\x06agents\x18\x01 \x03(\v2\x13.staff.v1.AgentInfoR\x06agents\"\x89\x01\n" +
	"\tAgentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12 \n" +
	"\vschedulable\x18\x05 \x01(\bR\vschedulable\",\n" +
	"\x0fGetStateRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xf5\x01\n" +
	"\n" +
	"AgentState\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_task\x18\x03 \x01(\tR\vcurrentTask\x125\n" +
	"\blast_run\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\alastRun\x125\n" +
	"\bnext_run\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\anextRun\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"1\n" +
	"\x12WatchStatesRequest\x12\x1b\n" +
	"\tagent_ids\x18\x01 \x03(\tR\bagentIds\"k\n" +
	"\x10ListInboxRequest\x12)\n" +
	"\x10include_archived\x18\x01 \x01(\bR\x0fincludeArchived\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"_\n" +
	"\x11ListInboxResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.staff.v1.InboxItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xd3\x01\n" +
	"\tInboxItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12\x1a\n" +
	"\barchived\x18\x06 \x01(\bR\barchived\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\")\n" +
	"\x0eArchiveRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"+\n" +
	"\x0fArchiveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x11WatchInboxRequest\x12\x1b\n" +
	"\tagent_ids\x18\x01 \x03(\tR\bagentIds\"w\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n" +
	"\vmemory_type\x18\x02 \x01(\tR\n" +
	"memoryType\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"B\n" +
	"\x0eSearchResponse\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.staff.v1.MemoryResultR\aresults\"\xc4\x02\n" +
	"\fMemoryResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1f\n" +
	"\vmemory_type\x18\x03 \x01(\tR\n" +
	"memoryType\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x02R\x05score\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12@\n" +
	"\bmetadata\x18\a \x03(\v2$.staff.v1.MemoryResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x01\n" +
	"\fStoreRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1f\n" +
	"\vmemory_type\x18\x02 \x01(\tR\n" +
	"memoryType\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12@\n" +
	"\bmetadata\x18\x04 \x03(\v2$.staff.v1.StoreRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\rStoreResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x10\n" +
	"\x0eGetInfoRequest\"\xdd\x01\n" +
	"\n" +
	"SystemInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12\x1f\n" +
	"\vsocket_path\x18\x04 \x01(\tR\n" +
	"socketPath\x122\n" +
	"\bdatabase\x18\x05 \x01(\v2\x16.staff.v1.DatabaseInfoR\bdatabase\"\x93\x01\n" +
	"\fDatabaseInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12!\n" +
	"\fmemory_count\x18\x03 \x01(\x05R\vmemoryCount\x12-\n" +
	"\x12conversation_count\x18\x04 \x01(\x05R\x11conversationCount\"-\n" +
	"\x10ListToolsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"=\n" +
	"\x11ListToolsResponse\x12(\n" +
	"\x05tools\x18\x01 \x03(\v2\x12.staff.v1.ToolInfoR\x05tools\"p\n" +
	"\bToolInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06schema\x18\x04 \x01(\tR\x06schema2\xe7\x02\n" +
	"\vChatService\x124\n" +
	"\x04Chat\x12\x15.staff.v1.ChatRequest\x1a\x13.staff.v1.ChatEvent0\x01\x12I\n" +
	"\x11GetOrCreateThread\x12\x1a.staff.v1.GetThreadRequest\x1a\x18.staff.v1.ThreadResponse\x12J\n" +
	"\vLoadHistory\x12\x1c.staff.v1.LoadHistoryRequest\x1a\x1d.staff.v1.LoadHistoryResponse\x12C\n" +
	"\fResetContext\x12\x18.staff.v1.ContextRequest\x1a\x19.staff.v1.ContextResponse\x12F\n" +
	"\x0fCompressContext\x12\x18.staff.v1.ContextRequest\x1a\x19.staff.v1.ContextResponse2\xde\x01\n" +
	"\fAgentService\x12G\n" +
	"\n" +
	"ListAgents\x12\x1b.staff.v1.ListAgentsRequest\x1a\x1c.staff.v1.ListAgentsResponse\x12@\n" +
	"\rGetAgentState\x12\x19.staff.v1.GetStateRequest\x1a\x14.staff.v1.AgentState\x12C\n" +
	"\vWatchStates\x12\x1c.staff.v1.WatchStatesRequest\x1a\x14.staff.v1.AgentState0\x012\xd1\x01\n" +
	"\fInboxService\x12D\n" +
	"\tListItems\x12\x1a.staff.v1.ListInboxRequest\x1a\x1b.staff.v1.ListInboxResponse\x12>\n" +
	"\aArchive\x12\x18.staff.v1.ArchiveRequest\x1a\x19.staff.v1.ArchiveResponse\x12;\n" +
	"\x05Watch\x12\x1b.staff.v1.WatchInboxRequest\x1a\x13.staff.v1.InboxItem0\x012\x86\x01\n" +
	"\rMemoryService\x12;\n" +
	"\x06Search\x12\x17.staff.v1.SearchRequest\x1a\x18.staff.v1.SearchResponse\x128\n" +
	"\x05Store\x12\x16.staff.v1.StoreRequest\x1a\x17.staff.v1.StoreResponse2\x90\x01\n" +
	"\rSystemService\x129\n" +
	"\aGetInfo\x12\x18.staff.v1.GetInfoRequest\x1a\x14.staff.v1.SystemInfo\x12D\n" +
	"\tListTools\x12\x1a.staff.v1.ListToolsRequest\x1a\x1b.staff.v1.ListToolsResponseB5Z3github.com/aschepis/backscratcher/staff/api/staffpbb\x06proto3"

var (
	file_staff_proto_rawDescOnce sync.Once
	file_staff_proto_rawDescData []byte
)

func file_staff_proto_rawDescGZIP() []byte {
	file_staff_proto_rawDescOnce.Do(func() {
		file_staff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_staff_proto_rawDesc), len(file_staff_proto_rawDesc)))
	})
	return file_staff_proto_rawDescData
}

var file_staff_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_staff_proto_goTypes = []any{
	(*ChatRequest)(nil),           // 0: staff.v1.ChatRequest
	(*ChatEvent)(nil),             // 1: staff.v1.ChatEvent
	(*TextDelta)(nil),             // 2: staff.v1.TextDelta
	(*ToolUse)(nil),               // 3: staff.v1.ToolUse
	(*ToolResult)(nil),            // 4: staff.v1.ToolResult
	(*ChatComplete)(nil),          // 5: staff.v1.ChatComplete
	(*ChatError)(nil),             // 6: staff.v1.ChatError
	(*GetThreadRequest)(nil),      // 7: staff.v1.GetThreadRequest
	(*ThreadResponse)(nil),        // 8: staff.v1.ThreadResponse
	(*LoadHistoryRequest)(nil),    // 9: staff.v1.LoadHistoryRequest
	(*LoadHistoryResponse)(nil),   // 10: staff.v1.LoadHistoryResponse
	(*Message)(nil),               // 11: staff.v1.Message
	(*ContextRequest)(nil),        // 12: staff.v1.ContextRequest
	(*ContextResponse)(nil),       // 13: staff.v1.ContextResponse
	(*ListAgentsRequest)(nil),     // 14: staff.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),    // 15: staff.v1.ListAgentsResponse
	(*AgentInfo)(nil),             // 16: staff.v1.AgentInfo
	(*GetStateRequest)(nil),       // 17: staff.v1.GetStateRequest
	(*AgentState)(nil),            // 18: staff.v1.AgentState
	(*WatchStatesRequest)(nil),    // 19: staff.v1.WatchStatesRequest
	(*ListInboxRequest)(nil),      // 20: staff.v1.ListInboxRequest
	(*ListInboxResponse)(nil),     // 21: staff.v1.ListInboxResponse
	(*InboxItem)(nil),             // 22: staff.v1.InboxItem
	(*ArchiveRequest)(nil),        // 23: staff.v1.ArchiveRequest
	(*ArchiveResponse)(nil),       // 24: staff.v1.ArchiveResponse
	(*WatchInboxRequest)(nil),     // 25: staff.v1.WatchInboxRequest
	(*SearchRequest)(nil),         // 26: staff.v1.SearchRequest
	(*SearchResponse)(nil),        // 27: staff.v1.SearchResponse
	(*MemoryResult)(nil),          // 28: staff.v1.MemoryResult
	(*StoreRequest)(nil),          // 29: staff.v1.StoreRequest
	(*StoreResponse)(nil),         // 30: staff.v1.StoreResponse
	(*GetInfoRequest)(nil),        // 31: staff.v1.GetInfoRequest
	(*SystemInfo)(nil),            // 32: staff.v1.SystemInfo
	(*DatabaseInfo)(nil),          // 33: staff.v1.DatabaseInfo
	(*ListToolsRequest)(nil),      // 34: staff.v1.ListToolsRequest
	(*ListToolsResponse)(nil),     // 35: staff.v1.ListToolsResponse
	(*ToolInfo)(nil),              // 36: staff.v1.ToolInfo
	nil,                           // 37: staff.v1.MemoryResult.MetadataEntry
	nil,                           // 38: staff.v1.StoreRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 39: google.protobuf.Timestamp
}
var file_staff_proto_depIdxs = []int32{
	2,  // 0: staff.v1.ChatEvent.text_delta:type_name -> staff.v1.TextDelta
	3,  // 1: staff.v1.ChatEvent.tool_use:type_name -> staff.v1.ToolUse
	4,  // 2: staff.v1.ChatEvent.tool_result:type_name -> staff.v1.ToolResult
	5,  // 3: staff.v1.ChatEvent.complete:type_name -> staff.v1.ChatComplete
	6,  // 4: staff.v1.ChatEvent.error:type_name -> staff.v1.ChatError
	39, // 5: staff.v1.ThreadResponse.created_at:type_name -> google.protobuf.Timestamp
	39, // 6: staff.v1.ThreadResponse.updated_at:type_name -> google.protobuf.Timestamp
	11, // 7: staff.v1.LoadHistoryResponse.messages:type_name -> staff.v1.Message
	39, // 8: staff.v1.Message.timestamp:type_name -> google.protobuf.Timestamp
	16, // 9: staff.v1.ListAgentsResponse.agents:type_name -> staff.v1.AgentInfo
	39, // 10: staff.v1.AgentState.last_run:type_name -> google.protobuf.Timestamp
	39, // 11: staff.v1.AgentState.next_run:type_name -> google.protobuf.Timestamp
	22, // 12: staff.v1.ListInboxResponse.items:type_name -> staff.v1.InboxItem
	39, // 13: staff.v1.InboxItem.created_at:type_name -> google.protobuf.Timestamp
	28, // 14: staff.v1.SearchResponse.results:type_name -> staff.v1.MemoryResult
	39, // 15: staff.v1.MemoryResult.created_at:type_name -> google.protobuf.Timestamp
	37, // 16: staff.v1.MemoryResult.metadata:type_name -> staff.v1.MemoryResult.MetadataEntry
	38, // 17: staff.v1.StoreRequest.metadata:type_name -> staff.v1.StoreRequest.MetadataEntry
	39, // 18: staff.v1.SystemInfo.started_at:type_name -> google.protobuf.Timestamp
	33, // 19: staff.v1.SystemInfo.database:type_name -> staff.v1.DatabaseInfo
	36, // 20: staff.v1.ListToolsResponse.tools:type_name -> staff.v1.ToolInfo
	0,  // 21: staff.v1.ChatService.Chat:input_type -> staff.v1.ChatRequest
	7,  // 22: staff.v1.ChatService.GetOrCreateThread:input_type -> staff.v1.GetThreadRequest
	9,  // 23: staff.v1.ChatService.LoadHistory:input_type -> staff.v1.LoadHistoryRequest
	12, // 24: staff.v1.ChatService.ResetContext:input_type -> staff.v1.ContextRequest
	12, // 25: staff.v1.ChatService.CompressContext:input_type -> staff.v1.ContextRequest
	14, // 26: staff.v1.AgentService.ListAgents:input_type -> staff.v1.ListAgentsRequest
	17, // 27: staff.v1.AgentService.GetAgentState:input_type -> staff.v1.GetStateRequest
	19, // 28: staff.v1.AgentService.WatchStates:input_type -> staff.v1.WatchStatesRequest
	20, // 29: staff.v1.InboxService.ListItems:input_type -> staff.v1.ListInboxRequest
	23, // 30: staff.v1.InboxService.Archive:input_type -> staff.v1.ArchiveRequest
	25, // 31: staff.v1.InboxService.Watch:input_type -> staff.v1.WatchInboxRequest
	26, // 32: staff.v1.MemoryService.Search:input_type -> staff.v1.SearchRequest
	29, // 33: staff.v1.MemoryService.Store:input_type -> staff.v1.StoreRequest
	31, // 34: staff.v1.SystemService.GetInfo:input_type -> staff.v1.GetInfoRequest
	34, // 35: staff.v1.SystemService.ListTools:input_type -> staff.v1.ListToolsRequest
	1,  // 36: staff.v1.ChatService.Chat:output_type -> staff.v1.ChatEvent
	8,  // 37: staff.v1.ChatService.GetOrCreateThread:output_type -> staff.v1.ThreadResponse
	10, // 38: staff.v1.ChatService.LoadHistory:output_type -> staff.v1.LoadHistoryResponse
	13, // 39: staff.v1.ChatService.ResetContext:output_type -> staff.v1.ContextResponse
	13, // 40: staff.v1.ChatService.CompressContext:output_type -> staff.v1.ContextResponse
	15, // 41: staff.v1.AgentService.ListAgents:output_type -> staff.v1.ListAgentsResponse
	18, // 42: staff.v1.AgentService.GetAgentState:output_type -> staff.v1.AgentState
	18, // 43: staff.v1.AgentService.WatchStates:output_type -> staff.v1.AgentState
	21, // 44: staff.v1.InboxService.ListItems:output_type -> staff.v1.ListInboxResponse
	24, // 45: staff.v1.InboxService.Archive:output_type -> staff.v1.ArchiveResponse
	22, // 46: staff.v1.InboxService.Watch:output_type -> staff.v1.InboxItem
	27, // 47: staff.v1.MemoryService.Search:output_type -> staff.v1.SearchResponse
	30, // 48: staff.v1.MemoryService.Store:output_type -> staff.v1.StoreResponse
	32, // 49: staff.v1.SystemService.GetInfo:output_type -> staff.v1.SystemInfo
	35, // 50: staff.v1.SystemService.ListTools:output_type -> staff.v1.ListToolsResponse
	36, // [36:51] is the sub-list for method output_type
	21, // [21:36] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_staff_proto_init() }
func file_staff_proto_init() {
	if File_staff_proto != nil {
		return
	}
	file_staff_proto_msgTypes[1].OneofWrappers = []any{
		(*ChatEvent_TextDelta)(nil),
		(*ChatEvent_ToolUse)(nil),
		(*ChatEvent_ToolResult)(nil),
		(*ChatEvent_Complete)(nil),
		(*ChatEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_staff_proto_rawDesc), len(file_staff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_staff_proto_goTypes,
		DependencyIndexes: file_staff_proto_depIdxs,
		MessageInfos:      file_staff_proto_msgTypes,
	}.Build()
	File_staff_proto = out.File
	file_staff_proto_goTypes = nil
	file_staff_proto_depIdxs = nil
}
